/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as GachaRouteImport } from './routes/gacha'
import { Route as IndexRouteImport } from './routes/index'

const GachaRoute = GachaRouteImport.update({
  id: '/gacha',
  path: '/gacha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gacha': typeof GachaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gacha': typeof GachaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gacha': typeof GachaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gacha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gacha'
  id: '__root__' | '/' | '/gacha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GachaRoute: typeof GachaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gacha': {
      id: '/gacha'
      path: '/gacha'
      fullPath: '/gacha'
      preLoaderRoute: typeof GachaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/gacha' {
  const createFileRoute: CreateFileRoute<
    '/gacha',
    FileRoutesByPath['/gacha']['parentRoute'],
    FileRoutesByPath['/gacha']['id'],
    FileRoutesByPath['/gacha']['path'],
    FileRoutesByPath['/gacha']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GachaRoute: GachaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
